package com.x.pojo;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_age
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_truename
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    private String userTruename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_age
     *
     * @return the value of users.user_age
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_age
     *
     * @param userAge the value for users.user_age
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_truename
     *
     * @return the value of users.user_truename
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public String getUserTruename() {
        return userTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_truename
     *
     * @param userTruename the value for users.user_truename
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public void setUserTruename(String userTruename) {
        this.userTruename = userTruename == null ? null : userTruename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role_id
     *
     * @return the value of users.role_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role_id
     *
     * @param roleId the value for users.role_id
     *
     * @mbg.generated Tue Aug 07 11:14:10 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}